kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "proxy2.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "proxy2.name" . }}
data:
  default.conf: |
    upstream app_server {
        server localhost:5000;
        keepalive {{ .Values.proxy.keepalive }};
    }
    server {
        listen 80;
        client_max_body_size {{ .Values.proxy.client_body_size }} ;
        server_name localhost;

        location = /favicon.ico { access_log off; log_not_found off; }

        location / {
            proxy_pass http://app_server ;
        }
    }